added XDG variables and separated cache from config

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,7 +3,7 @@
 # Check whether a command exists - returns 0 if it does, 1 if it does not
 exists()
 {
-  if command -v $1 >/dev/null 2>&1
+  if command -v "$1" >/dev/null 2>&1
   then
     return 0
   else
@@ -14,14 +14,14 @@ exists()
 # ask for user input (with custom text and default value)
 read_var()
 {
-  read -p "$1 (default $2): " var
+  read -r -p "$1 (default $2): " var
 
-  if [ -z $var ]
+  if [ -z "$var" ]
   then
-    var=$2
+    var="$2"
   fi
 
-  echo $var
+  echo "$var"
 }
 
 echo "MJM: a minimal job manager"
@@ -47,46 +47,57 @@ echo
 # get default params
 
 INSTALL_DIR=$( pwd )
-MJM_CONFIG_PATH=$HOME/.config/mjm/
+MJM_CONFIG_PATH="${XDG_CONFIG_HOME:-$HOME/.config}"/mjm/
+MJM_CACHE_PATH="${XDG_CACHE_HOME:-$HOME/.cache}"/mjm/
 
 echo "Please define:"
 
-MJM_LOCK_PATH=$( read_var "  location of lock file" $MJM_CONFIG_PATH/.lock )
-MJM_QUEUE_PATH=$( read_var "  location of queue directory" $MJM_CONFIG_PATH/queue/ )
+MJM_LOCK_PATH=$( read_var "  location of lock file" "$MJM_CACHE_PATH"/.lock )
+MJM_QUEUE_PATH=$( read_var "  location of queue directory" "$MJM_CACHE_PATH"/queue/ )
 MJM_MAX=$( read_var "  maximum number of simultaneous jobs" $(grep -c ^processor /proc/cpuinfo) )
 
 # create dir
 
 echo
 
-if ! mkdir $MJM_CONFIG_PATH; then
-  echo "Error: delete any prior installation of MJM to proceed."
+if ! mkdir "$MJM_CONFIG_PATH"; then
+  echo "Error: config files already exist in $MJM_CONFIG_PATH, delete directory to proceed."
   exit 1
 else
   echo "Created configuration directory $MJM_CONFIG_PATH"
 fi
 
-if ! mkdir $MJM_QUEUE_PATH; then
+if ! mkdir "$MJM_CACHE_PATH"; then
+  echo "Error: cache files already exist in $MJM_CACHE_PATH, delete directory to proceed."
+  exit 1
+else
+  echo "Created configuration directory $MJM_CACHE_PATH"
+fi
+
+if ! mkdir "$MJM_QUEUE_PATH"; then
   echo "Error"
   exit 1
 else
-  mkdir $MJM_QUEUE_PATH/very-high
-  mkdir $MJM_QUEUE_PATH/high
-  mkdir $MJM_QUEUE_PATH/normal
-  mkdir $MJM_QUEUE_PATH/low
-  mkdir $MJM_QUEUE_PATH/very-low
+  mkdir "$MJM_QUEUE_PATH"/very-high
+  mkdir "$MJM_QUEUE_PATH"/high
+  mkdir "$MJM_QUEUE_PATH"/normal
+  mkdir "$MJM_QUEUE_PATH"/low
+  mkdir "$MJM_QUEUE_PATH"/very-low
 
   echo "Created queue directories in $MJM_QUEUE_PATH"
 fi
 
 # write config file
 
-cat << EOF > $MJM_CONFIG_PATH/mjm.cfg
+cat << EOF > "$MJM_CONFIG_PATH"/mjm.cfg
 # Installation path
 export MJM_PATH=$INSTALL_DIR
 
 # Config dir location
 export MJM_CONFIG_PATH=$MJM_CONFIG_PATH
+
+# Cache dir location
+export MJM_CACHE_PATH=$MJM_CACHE_PATH
 
 # Global lock file
 export MJM_LOCK_PATH=$MJM_LOCK_PATH
@@ -101,6 +112,6 @@ EOF
 echo "Wrote configuration file $MJM_CONFIG_PATH/mjm.cfg"
 
 # create simlink
-mkdir $HOME/bin -p
-ln -s $INSTALL_DIR/mjm $HOME/bin/
-echo "Created simlink to ${HOME}/bin/"
+mkdir "$HOME"/bin -p
+ln -s "$INSTALL_DIR"/mjm "$HOME"/bin/
+echo "Created simlink to $HOME/bin/"
